### ISSUE TITLE
Blurry `Lines` when zoomed

### ISSUE THREAD

**Issue by mxdvl** [guardian/source#1319]
**Describe the bug**
As reported by @paperboyo:

> Them gradient lines always inconsistent widths on zoom in Firefox
> No idea if there is a way of working around this Firefox bug, but they look for me like this more often than not as they are now (always have):

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/76776/161956856-1f4cb61b-d925-41f1-8866-7f54edfcb5fd.png)

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: Firefox
-   Version: [e.g. 22]

**Additional context**
Browser is zoomed **115%**

**Comment by paperboyo** [comment]
Thx! Basically, Firefox seem to render them lines at different widths when you zoom in and out. They should (possibly) be same width at all zoom levels. Just as these are:

![image](https://user-images.githubusercontent.com/6032869/161957847-3a775ff2-a849-489b-b932-4fca56c9f4ad.png)

![image](https://user-images.githubusercontent.com/6032869/161957918-779df544-652a-4d86-bb28-d89e06dfe362.png)

(hush-hush: Chrome, which is good at lines, is a bit worse at dots than Firefox, but only marginally)
