### ISSUE TITLE
Untangling emotion from source-foundations

### ISSUE THREAD

**Issue by ashishpuliyel** [guardian/source#1574]
## Background
In some cases, we are exporting Emotion CSS from source-foundations. This goes against the principle that source-foundations should be agnostic as to which css-in-js frameworks it supports.

It also breaks the build for AMP in DCR, because it makes the assumption that some of the CSS we export is not Emotion CSS.

## Work done

Original PR that was closed and split into the two below for clarity: 
https://github.com/guardian/source/pull/1554

- Fixes CSS and adds tests to ensure it is valid: https://github.com/guardian/source/pull/1566
- Proposal for a possible approach to indicate where we export Emotion CSS: https://github.com/guardian/source/pull/1568

**Comment by ob6160** [comment]
Following some discussion on https://github.com/guardian/source/pull/1568, we've decided to pause work on this and discuss our approach towards removing the dependency on emotion that we have in `source-foundations` instead of potentially setting it in stone by adding it as a peer dependency.
