### ISSUE TITLE
Text input field label should be bold

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#280]
**Describe the bug**
 The input label should be bold by default

**Screenshots**

Live example:

<img width="539" alt="Screenshot 2020-03-18 at 21 26 20" src="https://user-images.githubusercontent.com/5931528/77009072-35952d80-695f-11ea-88d0-297aee9b2566.png">

(https://www.theguardian.design/2a1e5182b/p/097455-text-input-field/b/050445)

In Figma:

<img width="475" alt="Screenshot 2020-03-18 at 21 28 07" src="https://user-images.githubusercontent.com/5931528/77009193-683f2600-695f-11ea-860a-f2c74737c6a5.png">

(https://www.figma.com/file/qY0C090LN6LDAqdzmV2FsA/Text-inputs?node-id=7%3A360)

**Comment by webb04** [comment]
🙋‍♂️Taking a look at this one.

**Comment by SiAdcock** [comment]
FIxed by #296
