### ISSUE TITLE
Font Style Normal

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/source#292]
https://github.com/guardian/source/blob/d42e9821c4bd1d7a7ac2a01a00be7b5821987117/src/core/foundations/src/typography/fs.ts#L30

As `italic` is an optional parameter for fonts, there are three states it can be in: `true`, `false` and `undefined`. Should `font-style` be set explicitly to `normal` when `italic` is set explicitly to `false`? In essence, the following:

<dl>
  <dt>true</dt>
  <dd><code>font-style: italic;</code></dd>
  <dt>false</dt>
  <dd><code>font-style: normal;</code></dd>
  <dt>undefined</dt>
  <dd><code>""</code></dd>
</dl>

This is useful for times when you want to explicitly set `font-style: normal;`. For example, when overriding the user agent italic styles for [`<address>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/address).

**Comment by SiAdcock** [comment]
I like that, let's roll with it! Thanks for suggesting @JamieB-gu. Do you fancy raising a PR?

**Comment by JamieB-gu** [comment]
I've discovered that because there are [defaults specified](https://github.com/guardian/source/blob/d42e9821c4bd1d7a7ac2a01a00be7b5821987117/src/core/foundations/src/typography/api.ts#L15) for each font, the `undefined` value never actually makes it through. Therefore I think we have two options:

1) Always explicitly set `font-style`, to either `italic` or `normal`
2) Make the `italic` property "optional", so that it's `undefined` by default, and don't set `font-style` when that's the case

**Comment by SiAdcock** [comment]
I think the second option sounds reasonable. It's a breaking change, but I think it'll be manageable because I doubt many people (anyone?) is currently relying on the default explicitly adding `font-style: normal`.

**Comment by JamieB-gu** [comment]
Ok, can do that.

Why do you prefer 2) over 1) out of curiosity?

**Comment by SiAdcock** [comment]
@JamieB-gu 

- to preserve some semblance of the cascade / UA styling
- to reduce the amount of CSS that gets shipped

**Comment by JamieB-gu** [comment]
Do you think there's any value in creating a custom type for this?

```ts
type FontStyle = 'italic' | 'normal' | 'unset';
```

or

```ts
const enum FontStyle {
    Italic,
    Normal,
    Unset,
}
```

**Comment by SiAdcock** [comment]
Interesting. It raises a few questions for me (sorry for bombardment, feel free to chat me if easier!)

To be clear, are you proposing a change to the API from:

```js
textSans.medium({ italic: true })
```

to:

```js
textSans.medium({ fontStyle: 'italic' })
```
?

How does unset differ from not providing any value for `font-style`?

Would unset be the default if `fontStyle` is not specified?

Unset is a great property, but unsupported in IE11. I wonder what the behaviour would be there?

**Comment by JamieB-gu** [comment]
> are you proposing a change to the API

Yes 🙂

> How does unset differ from not providing any value for font-style?
> Unset is a great property, but unsupported in IE11. I wonder what the behaviour would be there?

It doesn't, I was just using `Unset` for the value representing the case when it's not set. It could be any name really, I used that one because it's a familiar term in the CSS world.

> Would unset be the default if fontStyle is not specified?

I see that as being the default if the user passes nothing:

```ts
textSans.medium()
```

 I guess it could just as easily be `Option<FontStyle>` where `FontStyle` is the narrower:

```ts
type FontStyle = 'italic' | 'normal'
```

**Comment by SiAdcock** [comment]
The 👍s have spoken:

<img width="946" alt="Screenshot 2020-03-26 at 14 16 04" src="https://user-images.githubusercontent.com/5931528/77656827-59163480-6f6c-11ea-8aa4-42133c9db413.png">

It was always going to be a breaking change anyway, we might as well go all-in and change the API up completely! I agree with the change, it makes it clearer, is more predictable and extensible.

I prefer the `Option<FontStyle>` approach. I think `Unset` adds clutter to the API and seems to promise something it doesn't deliver.

We should preserve the old `italic: boolan` API for legacy purposes, to give people the opportunity to migrate. When we feel confident that not many people are using it, we can remove it.

**Comment by JamieB-gu** [comment]
Based on a discussion on this, the proposed API would be consumed like this (via @SiAdcock):

```ts
textSans.medium() // no font-style property
textSans.medium({ fontStyle: 'normal' }) //font-style: normal
textSans.medium({ fontStyle: 'italic' }) //font-style: italic
```
