### ISSUE TITLE
Add ChromaticQA

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#293]
**Describe the solution you'd like**

DCR has been using [ChromaticQA](https://www.chromaticqa.com/) to excellent effect for cross-browser, multi-breakpoint visual regression testing. Since we now have a standard licence, we can start using it in other codebases too. Source will find a lot of benefit from it, especially cross-browser testing.

**Comment by oliverlloyd** [comment]
I've created a [new project](https://www.chromaticqa.com/builds?appId=5e933197d94d9c002275a15e) and [added the lib](https://github.com/guardian/source/pull/324) to run Chromatic snapshots.

### Next steps
Either configure your CI server to run the snapshot on each push or add a [github action](https://github.com/chromaui/action) to do it. We've been using Github actions over in [DCR](https://github.com/guardian/dotcom-rendering/blob/master/.github/workflows/chromatic.yml) and [Discussion](https://github.com/guardian/discussion-rendering/blob/master/.github/workflows/chromatic.yml) with success. You just need to add the workflow and create github secret for `CHROMATIC_APP_CODE`. If you can't see the app code in Chromatic ask me and I can ping it to you.

**Comment by SiAdcock** [comment]
Fixed in #324, thanks @oliverlloyd 🎉
