### ISSUE TITLE
Prevent CI action running on both master and gh-pages branches

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#304]
**Describe the bug**
Currently the CI action runs on both `master` and `gh-pages` branches. This is unnecessary

**Expected behavior**
Only the Deploy to GitHub Pages action should run on `master`. We don't need any actions to run explicitly on `gh-pages`.

**Comment by JamieB-gu** [comment]
Is it this line that you're talking about here?

https://github.com/guardian/source/blob/0b9bceeaa9ebe0d45d2e62f8f9069db907ee53fa/.github/workflows/ci.yml#L5

**Comment by SiAdcock** [comment]
Yeah. So I want the CI workflow to run only on branches that are not called `master` or `gh-pages`. Is that possible, do you know? My regex / globby skills failed me!

**Comment by JamieB-gu** [comment]
Based on my reading of the docs, I *think* that PR should do it.
