### ISSUE TITLE
@guardian/src-svgs is missing the esm build

### ISSUE THREAD

**Issue by sndrs** [guardian/source#328]
**Describe the bug**
`@guardian/src-svgs` `dist` dir only includes a cjs `index.js`, but the package declares:

```json
"main": "dist/index.js",
"module": "dist/index.esm.js",
``` 

Running `yarn build` in `src/core/svgs` _does_ generate the file though.

**To Reproduce**
1. `yarn add @guardian/src-svgs`
2. look in `node_modules/@guardian/src-svgs/dist`

**Expected behavior**
Both files should exist

cc @ripecosta

**Comment by SiAdcock** [comment]
Oh lordy, good catch! Rather annoying that `npm` will implicitly include the `main` file but not the `module` file. 

This might explain why the footprint of `src-svgs` is so large in DCR, despite the fact barely any are being used!

![Screenshot 2020-04-16 at 16 08 41](https://user-images.githubusercontent.com/5931528/79473187-b1d16e00-7ffc-11ea-8605-ec8789d3cd9b.png)

**Comment by sndrs** [comment]
> Rather annoying that npm will implicitly include the main file but not the module file.

ah man, yeah! yeah this was using rollup and we coudn't work out why it was complaining it needed `namedExports` and `resolve` help. i guess webpack would happily enough just keep going with the `main` field if `module` failed, but rollup wouldn't without help

**Comment by SiAdcock** [comment]
> i guess webpack would happily enough just keep going with the main field if module failed, but rollup wouldn't without help

Interesting point of contrast. `Fail fast` vs `Avoid failure at all costs`!
