### ISSUE TITLE
Atom components

### ISSUE THREAD

**Issue by webb04** [guardian/source#341]
We've had some discussions about where Atoms could live for dotcom-rendering and apps-rendering and whether they can be shared. Would the design system be a good place to keep atom components? 

Possible alternatives:
- Continue developing separately on apps-rendering, dotcom-rendering and maybe editions?
- Share atom components in a different repo/package

I've made a [pr](https://github.com/guardian/apps-rendering/pull/298) to add interactive atoms to apps-rendering but I think other atom types would be easier to make into React components.

**Comment by oliverlloyd** [comment]
What's an Atom?

Sounds like a facetious comment but is actually genuine. I see this word used a lot in various contexts and I've never really been able to figure it out

**Comment by JamieB-gu** [comment]
@philmcmahon @akash1810 @tomrf1 would you be able to give a brief summary of what atoms are?

**Comment by SiAdcock** [comment]
Hi @webb04 

I understand atoms to be platform agnostic, individually publishable and embeddable pieces of content. There are a number of atom types (quizzes, recipes, charts, etc) that all conform to a contract understood by our platforms (frontend and the live news apps). New atoms are built by editorial using [Atom Workshop](https://atomworkshop.gutools.co.uk/find). The web templates for supported atom types live in the [Atom Renderer](https://github.com/guardian/atom-renderer/tree/master/core/src/main/resources) repo.

In my opinion, Source is not the right place to define atom types. Source defines the visual language of the Guardian and its products. It's a resource for designers and developers to help bring new experiences to our readers and subscribers faster. It's not a place simply for components that need to be shared across applications.

If the intention is to rebuild atom-renderer and the atom types using a stack that is closer to our other frontend products (i.e. (P)React(-native), Emotion), then I think it should be implemented as a separate concern, albeit using components defined in Source.

That said, I'd be interested to hear what others think 🙂 

c/c @gtrufitt @ajwl

**Comment by philmcmahon** [comment]
Just to add from Simon's explanation - technically an atom is a thing with these fields: https://github.com/guardian/content-atom/blob/master/thrift/src/main/thrift/contentatom.thrift#L43

^ that also has a list of all the current atom types. 

Almost all videos on the website are wrapped inside a 'media atom' which helps keep track of the youtube metadata etc.

**Comment by gtrufitt** [comment]
> If the intention is to rebuild atom-renderer and the atom types using a stack that is closer to our other frontend products (i.e. (P)React(-native), Emotion), then I think it should be implemented as a separate concern, albeit using components defined in Source.

+1

cc/ @shtukas - at the moment we're just moving forward with atom renderer

**Comment by akash1810** [comment]
Agreed with @SiAdcock. Source isn't the right home for atoms. Would be better for Atom Renderer to be a consumer of Source. This keeps a nice separation of concerns and keeps Source unopinionated as it just cares about the fundamentals (button, input, etc) rather than article elements.

**Comment by webb04** [comment]
Thanks all. Would be good to discuss what you were planning with atom renderer @gtrufitt @shtukas. Atoms are one of the last things we need to support in articles for apps-rendering so it would be good to know if we can contribute to that work!
