### ISSUE TITLE
Larger Text Sans For Guardian Labs

### ISSUE THREAD

**Issue by JamieB-gu** [guardian/source#343]
**Is your feature request related to a problem? Please describe.**

Headlines on Guardian Labs articles appear in a `Text Sans` font, at a size of `34px` (example [here](https://www.theguardian.com/women-engineering-infrastructure-atkins/2020/apr/01/its-an-exciting-time-for-engineers-the-path-to-decarbonising-the-uks-energy-mix)). The largest size offered by Source for `Text Sans` is `24px` (see [here](https://www.theguardian.design/2a1e5182b/p/930d69-typography/t/4270c1)).

**Describe the solution you'd like**

A larger `Text Sans` to be exposed by the typography module, providing a `34px` version e.g.:

```ts
textSans.xxlarge()
```

**Describe alternatives you've considered**

There's also a `Guardian Sans Web` font that was previously used for sans headlines, but I think we moved away from that (@paperboyo could probably confirm).

**Additional context**

See the discussion on apps-rendering [here](https://github.com/guardian/apps-rendering/pull/300#discussion_r416698134).

**Comment by paperboyo** [comment]
> `Guardian Sans Web` font

Yeah. We don’t have new versions of it. Also, we do not load it on dotcom. Also, We never had license to use the full family on the web/apps.

**Comment by webb04** [comment]
Going to raise a PR, please stop me or reject it if not wanted.
