### ISSUE TITLE
Additional icons for apps-rendering

### ISSUE THREAD

**Issue by webb04** [guardian/source#371]
We are still using an icon font in apps-rendering but would like to use the SVG icons in source.

There's some icons missing we would need before fully removing that icons font:
- Camera
- Stars
- Quote
- Comment

I've got a Figma file with these SVGs so I could make a PR to add them, would this be useful?

<img width="203" alt="Screen Shot 2020-05-28 at 11 45 58" src="https://user-images.githubusercontent.com/11618797/83132260-06c2d280-a0d9-11ea-9c9f-c41b357ca8df.png">
<img width="48" alt="Screen Shot 2020-05-28 at 11 46 20" src="https://user-images.githubusercontent.com/11618797/83132261-07f3ff80-a0d9-11ea-8971-91d429a9e979.png">
<img width="102" alt="Screen Shot 2020-05-28 at 11 45 40" src="https://user-images.githubusercontent.com/11618797/83132262-07f3ff80-a0d9-11ea-96db-5b15393f4ee8.png">

**Comment by paperboyo** [comment]
> Quote

Out of curiosity, which one are we talking about? There were so many…

**Comment by webb04** [comment]
We're using this one on apps

![IMG_5297](https://user-images.githubusercontent.com/11618797/83137850-c025a600-a0e1-11ea-919e-5aee968eb663.PNG)

**Comment by SiAdcock** [comment]
Thanks @webb04 . We have the camera, star and comment icons [in Figma already](https://www.figma.com/file/Ai7AELHC6KCz38qKZkvuHo/Icons?node-id=55%3A2), we just need to add React versions of the SVGs to the [`svgs`](https://github.com/guardian/source/tree/master/src/core/svgs) and [`icons`](https://github.com/guardian/source/tree/master/src/core/icons) packages.

The quote icon is interesting, it seems like it belongs in [Editorial Source](https://github.com/guardian/source/tree/master/src/editorial). Should we create an editorial icons package?

c/c @gtrufitt @oliverlloyd @liywjl @JamieB-gu

**Comment by JamieB-gu** [comment]
I think there's a reasonable chance of the quote icon showing up elsewhere, e.g. Reader Revenue. It's currently in a few places on the Patrons site for example.

**Comment by SiAdcock** [comment]
@JamieB-gu that's good to know, thanks!

@webb04 If you could share the quote icon, I'll add it to Figma, and then to the Source repo and the Source website :relaxed:

**Comment by webb04** [comment]
I found this in one of @benwuersching 's designs

[quote.svg.zip](https://github.com/guardian/source/files/4696527/quote.svg.zip)

**Comment by SiAdcock** [comment]
Thanks for sharing the file @webb04. Sorry, I got a bit carried away and implemented these additions myself 🙄 

Please let me know if there's any issue.
