### ISSUE TITLE
RFC: Layout components

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#526]
From #488, there was broad agreement in favour of a JSX-based API. I've started spiking a set of layout components.

# Abandoning the Grid components

I have moved away from the existing [Grid component API](https://theguardian.design/2a1e5182b/p/978527--grid-component/b/304251) for a few reasons:

1. The columns / spans abstraction is confusing and hard to remember. It expects the developer to know how many columns are available at each breakpoint. 
2. It provides an unnecessarily high granularity of control, making the API weighty for no good reason.
3. The name "Grid" is confusing and means too many things.
4. It tries (and fails) to be a one-stop solution for all layouts.

# Layout spiking

A number of developers and designers have kindly shared layouts that they are currently working on. Over the last few days I've built a number of them, noting layout similarities and patterns.

- Checkout flow
- Consents flow
- Thank you flow
- Article on web
- Showcase in Editions

As a result of this spike, I've identified 5 new layout components that, when combined, can be used to build (nearly) all of these layouts.

- Container
- Stack
- Columns / Column
- Tiles
- Hide

This work has been greatly inspired by awesome open source component libraries such as [Braid](https://seek-oss.github.io/braid-design-system/foundations/layout) and [Chakra-UI](https://chakra-ui.com/getting-started).

## Container

```tsx
<Container>
  <article></article>
</Container>
```

The Container centres the page content and applies a width that corresponds to the grid at the current breakpoint.

## Stack

```tsx
<Stack>
  <div></div>
  <div></div>
  <div></div>
</Stack>
```

Children will be stacked one on top of the other.

## Columns / Column

```tsx
<Columns>
  <Column width={1/4}></Column>
  <Column width={1/4}></Column>
  <Column></Column>
</Columns>
```

Columns will be arranged side by side on a single row, with the specified width.

`width`: If no value is provided, the column width will be fluid (i.e. take up remaining space, divided between all fluid columns).

## Tiles

```tsx
<Tiles columns={3}>
  <div></div>
  <div></div>
  <div></div>
  <div></div>
</Tiles>
```

Items will be arranged with equal width and spacing with the specified number of columns, wrapping onto a new row as necessary.

## Hide

```tsx
<Hide above="tablet">
  <MobileNavigation />
</Hide>
<Hide below="desktop">
  <DesktopNavigation />
</Hide>
```

Hide a component above or below a certain breakpoint

# Request for comments

The exact API for each of these components is yet to be finalised. I'll request input for this, component-by-component at a later date.

I'd like to know whether this approach is something that would work for you and your team, and would solve most of your common layout issues? Also if you can think of any more components or abstractions that would be useful, please add them to this issue.

**Comment by TomPretty** [comment]
I'm so onboard for all of these! 

## Container

This looks neat - I think I'm effectively doing something similar right now:

```js
const container = css`
  margin: 0 auto;

  ${from.tablet} {
    max-width: 740px;
  }

  ${from.desktop} {
    max-width: 980px;
  }

  ${from.wide} {
    max-width: 1300px;
  }
`;
```

Would happily swap this out for a `<Container />`!

## Stack

Yes. I think it would be great to have the option of horizontal/vertical. If I could do something like:

```jsx
<Stack horizontal>
  <FacebookSocialShare />
  <TwitterSocialShare />
  <LinkedInSocialShare />
  <EmailSocialShare />
</Stack>
```
To get 

<img width="257" alt="Screenshot 2020-09-09 at 15 44 53" src="https://user-images.githubusercontent.com/17720442/92614075-8b65e500-f2b3-11ea-9e3a-b9d90af8e260.png">

I'd be super happy.

## Columns

👍

## Tiles

👍

## Hide

🔥🔥. This would be so useful. Perhaps the props could be `from`, `until`, and `between` to align with current mq naming.

**Comment by SiAdcock** [comment]
@TomPretty 

> I think it would be great to have the option of horizontal/vertical.

Cool idea! In order to preserve the "do one thing" spirit of these components, I might propose a sixth component for that:

## Inline

```
<Inline>
  <FacebookSocialShare />
  <TwitterSocialShare />
  <LinkedInSocialShare />
  <EmailSocialShare />
</Inline>
```

Children will be laid out one next to the other.

> Perhaps the props could be from, until, and between to align with current mq naming.

This is a great point! Thanks 🙏

**Comment by nicl** [comment]
👍 this feels like a good, simple, help for common layout stuff.

**Comment by mxdvl** [comment]
Hopefully we’ll be able to use this on the new engineering website, as well!

**Comment by SiAdcock** [comment]
@frankie297 has kindly agreed to look at the Tiles component.

@amyhughes is currently working on the Inline component

**Comment by SiAdcock** [comment]
All proposed layout components have now been implemented
