### ISSUE TITLE
Back to top link protrudes in footer

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#550]
**Describe the bug**

The back to top link sits along the horizontal boundary line of the footer, and as such protrudes outside of the footer bounding box (see screenshot). This looks odd if the container above the footer is not the same colour as the footer itself. This means the footer component is making an assumption about surrounding components, making it [less reusable](https://www.theguardian.design/2a1e5182b/p/11c92e-acceptance-criteria/t/3841ef)/

**Expected behavior**

The footer should always be square. The back to top link should not escape from the boundaries of the footer.

**Screenshots**

![93223211-b777df00-f767-11ea-936d-3d4f56d100b0](https://user-images.githubusercontent.com/5931528/94816383-a4197480-03f3-11eb-98b8-5fe6b60a9391.png)

**Comment by norahumasi** [comment]
Hello, can you assign this issue to me? Thank you!

**Comment by norahumasi** [comment]
> @norahumasi sure thing! 
> 
> Thanks for taking a look. Let me know if I can help in any way

Hi, can you help me run it? I just did yarn and yarn storybook and it seens compiling and running fine but when I access localhost:9009 nothing happens. Thank you!

**Comment by SiAdcock** [comment]
Interesting, let’s see what’s up. What operating system are you using? And would you be able to copy-paste the output from running yarn storybook? Many thanks

**Comment by SiAdcock** [comment]
Hi @norahumasi, did you manage to get Storybook up and running? Please let me know if you need any help 🙂

**Comment by mathieumure** [comment]
@SiAdcock I can also work on it, if it's still available

**Comment by SiAdcock** [comment]
You are storming @mathieumure! 👍

**Comment by mathieumure** [comment]
Hi, @SiAdcock, I just submit a PR that's makes the back to top button included inside the footer. Tell me if the angle of the correction suits you.
