### ISSUE TITLE
Allow consumer to visually hide text labels

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#555]
**Is your feature request related to a problem? Please describe.**

It is not always necessary to visually show a text label above a user input field such as text input field, text area or select box. An example would be when there is a single user input field on the page and there is enough additional context on the page to inform the user what kind of data is required.

<img width="1495" alt="Screenshot_2020-05-28_at_11 41 55" src="https://user-images.githubusercontent.com/5931528/94923864-75af9e00-04b4-11eb-8f81-49e61ef2760e.png">

**Describe the solution you'd like**

It should be possible for the consumer of these components to visually hide the text label of a user input field. We could achieve this by expanding the API of our user input field components to include a new prop:

```ts
{
  hideLabel: boolean
}
```

The naming here is consistent with the [same feature in the Button component](https://github.com/guardian/source/blob/4637c1142c1b2063e08fa1167354408c5b980173/src/core/components/button/index.tsx#L157).

By default, this prop is set to `false`. If set to true, the text label is visually hidden. The text label will still be read by a screen reader.

This solution should be applied to the following components:

- [ ] [TextInput](https://github.com/guardian/source/tree/main/src/core/components/text-input)
- [ ] [TextArea](https://github.com/guardian/source/tree/main/src/core/components/text-area)
- [ ] [Select](https://github.com/guardian/source/tree/main/src/core/components/select)
- [ ] [RadioGroup](https://github.com/guardian/source/tree/main/src/core/components/radio)
- [ ] [CheckboxGroup](https://github.com/guardian/source/tree/main/src/core/components/checkbox)

**Comment by Agreon** [comment]
I would love to try that :)

**Comment by SiAdcock** [comment]
@Agreon That's great, thanks so much! Let me know which component(s) you'd like to work on and I can assign you 😄

**Comment by Agreon** [comment]
I guess i will have a look at TextInput first.. If that's not big of a change or others claim them, i could add the others as well.

**Comment by SiAdcock** [comment]
Thanks @Agreon. Please let me know if you need any help getting started

**Comment by Agreon** [comment]
@SiAdcock I have one question: If the prop "hideLabel" is set, should the optional text also not be shown?

**Comment by SiAdcock** [comment]
Good question. I say we hide that "Optional" text also. It would look weird to have that dangling there on its own 😄

**Comment by Agreon** [comment]
@SiAdcock Is there already some handling in the code i can take as an example for only hiding things visually? Screen reader support seems [interesting](https://stackoverflow.com/questions/26032089/in-html-how-can-i-have-text-that-is-only-accessible-for-screen-readers-i-e-fo)

**Comment by SiAdcock** [comment]
Sure! You can take a look at [how the button component](https://github.com/guardian/source/blob/4637c1142c1b2063e08fa1167354408c5b980173/src/core/components/button/index.tsx#L111-L123) achieves this behaviour. It uses the [`visuallyHidden`](https://www.theguardian.design/2a1e5182b/p/6691bb-accessibility/t/1285a8) CSS snippet (defined [here](https://github.com/guardian/source/blob/4637c1142c1b2063e08fa1167354408c5b980173/src/core/foundations/src/accessibility/index.ts#L3-L10))
