### ISSUE TITLE
React warning on passing prop to DOM element

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#556]
**Describe the bug**

In Storybook we're seeing the following error in dev on the [icon-only link button story](http://localhost:9009/?path=/story/button--icon-only-link-buttons) (<-- this link only works when running `yarn storybook` locally)

```
Warning: React does not recognize the `showIcon` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `showicon` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Context.Consumer)
    in EmotionCssPropInternal (created by LinkButton)
    in LinkButton
    in div (created by storyFn)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by storyFn)
    in div (created by storyFn)
    in storyFn
    in ErrorBoundary
```

This is because we are passing the (now unused) [showIcon prop](https://github.com/guardian/source/blob/4637c1142c1b2063e08fa1167354408c5b980173/src/core/components/button/index.tsx#L250) to the DOM in the LinkButton component. We could delete this prop entirely.

**Expected behavior**

We should not pass this prop to the underlying DOM element, so this warning would not appear

**Comment by kala2** [comment]
Hello, could you assign it to me please?

**Comment by SiAdcock** [comment]
Certainly, thanks @kala2 🙏

**Comment by kala2** [comment]
Sorry, issue is available for someone else to take it

**Comment by g-ravity** [comment]
I can take up this issue. Please assign me, if this is still available.

**Comment by SiAdcock** [comment]
@g-ravity thanks so much, it's all yours!

**Comment by SiAdcock** [comment]
Hi @g-ravity, are you still able to work on this? Let me know if you need any help 😄

**Comment by mathieumure** [comment]
Hi, I can work on that if you want @SiAdcock 😄

**Comment by SiAdcock** [comment]
Oh cool, nice to see you again! Thanks @mathieumure 😄

**Comment by mathieumure** [comment]
@SiAdcock here is the fix, tell me if it suits your need 👉  https://github.com/guardian/source/pull/567
