### ISSUE TITLE
React warning on LinkButton: each child should have a key prop

### ISSUE THREAD

**Issue by SiAdcock** [guardian/source#558]
**Describe the bug**

In Storybook we're seeing the following warning in dev on the [link button story](http://localhost:9009/?path=/story/button--priority-link-buttons-light) (<-- this link only works when running `yarn storybook` locally)

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `LinkButton`. See https://fb.me/react-warning-keys for more information.
    in div (created by LinkButton)
    in LinkButton
    in div (created by storyFn)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by storyFn)
    in div (created by Context.Consumer)
    in EmotionCssPropInternal (created by storyFn)
    in div (created by storyFn)
    in storyFn
    in ErrorBoundary
```
I believe this is due to the way we're composing elements using an array (see [possible culprit](https://github.com/guardian/source/blob/3d412147c96cff6722286116f58f31ec2ed77ba7/src/core/components/button/index.tsx#L107))

**Expected behavior**

We should pass a `key` prop to elements composed using arrays, or we should explicitly disable the lint rule for this case.

**Comment by mathieumure** [comment]
I can work on that if you want

**Comment by SiAdcock** [comment]
@mathieumure thanks so much! 🙏 Let me know if you need any help

**Comment by mathieumure** [comment]
@SiAdcock I submit a pull request to fix it :wink: :point_right:  https://github.com/guardian/source/pull/559
Tell me if is it ok for you ?

**Comment by mathieumure** [comment]
@SiAdcock, as you have multiple hacktoberfest tags in your issues, I suggest you to add the `hacktoberfest` topic on your repository description 😉 . More info here 👉 https://twitter.com/hacktoberfest/status/1312221208667185153

**Comment by SiAdcock** [comment]
@mathieumure Thanks for letting me know, I've done that now 👍
