### ISSUE TITLE
Buttons prop `children` mandatory

### ISSUE THREAD

**Issue by liywjl** [guardian/source#575]
**Is your feature request related to a problem? Please describe.**
Buttons `children` prop are mandatory, however they should be optional.

**Describe the solution you'd like**
Make `children` prop optional.

**Comment by SiAdcock** [comment]
Hi @liywjl, can you give me an example of where this would be useful? Note if you want only an icon to be visible, you can pass the [`hideLabel`](https://theguardian.design/2a1e5182b/p/435225-button/t/079205) prop

**Comment by liywjl** [comment]
Here is an example of a work around we had to do in a recent update because `children` was a mandatory prop: https://github.com/guardian/discussion-rendering/pull/345/files#diff-b5928ae26d810ad0f00591179422632ce95a546bf892f9a776ace078f7b19d4dR296-R308

**Comment by liywjl** [comment]
we had to add an empty object as child to satisfy the prop requirement:
```
<Button icon={XXX} hideLabel={true}>{}</Button>
```

ideally we wouldn't need to add the empty object:
```
<Button icon={XXX} hideLabel={true}/>
```

**Comment by SiAdcock** [comment]
Thanks @liywjl. The reason we make the children mandatory is to ensure something is announced to screen readers. Can you think of some text you can add that will help a screen reader user understand the purpose of the button? Apologies if you have implemented an alternative way of doing this.

**Comment by liywjl** [comment]
I see that makes a lot more sense! I think however this behaviour isn't quite obvious, I noticed others leaving the object blank as well during upgrade. I am unsure what might be the best way of communicating this to other developers? Maybe add some documentation? Maybe use a separate prop for description?

**Comment by SiAdcock** [comment]
Yes, it sounds like a tricky one. I agree the docs need more clarity regarding this.

> a separate prop for description

Can you flesh out that proposal a little? Do you mean an optional prop that would be announced by screen readers when children are not passed? At this point, we need to make the (unsafe and untrue) assumption that everybody is testing their work with a screen reader, and that they question how to ensure that a button with no text label is still announced by a screen reader.

> I noticed others leaving the object blank as well during upgrade

That's not good 😞 My expectation was that if the API caused friction like this, people would question why that friction exists and try to address it. Perhaps they checked the docs and the docs weren't obvious, so they assumed it was a bug, found a workaround and moved on? It's good that you raised the question here.

**Comment by SiAdcock** [comment]
>  the docs need more clarity regarding this.

I've added an [Accessibility](https://theguardian.design/2a1e5182b/p/435225-button/t/80e083) section near the top of the Button documentation. Let me know if you think this will be helpful or if it could be improved.

**Comment by liywjl** [comment]
Thanks for adding this 👍  I think this is a good step, if I have any better ideas I will share
