### ISSUE TITLE
Revert work around for chrome browser

### ISSUE THREAD

**Issue by liywjl** [guardian/source#580]
Regarding the issue raised here:
https://github.com/guardian/source/blob/main/src/core/components/radio/styles.ts#L118

it appears that it has been resolved:
https://bugs.chromium.org/p/chromium/issues/detail?id=375693#c88

We should therefore revert back to `display: flex`.

Note:
The `display:block` and `vertical-align:middle` work around did not seem to work for DCR (example below). I will do a workaround in the meantime to force `display: flex` for the Radio wrapper.

Before Update:
<img width="607" alt="Screenshot 2020-10-22 at 13 51 14" src="https://user-images.githubusercontent.com/8831403/96874249-d3108c80-146d-11eb-89e2-c789cdfe8b62.png">

After Update:
<img width="569" alt="Screenshot 2020-10-22 at 13 51 07" src="https://user-images.githubusercontent.com/8831403/96874266-d73caa00-146d-11eb-93e4-eacb87e6006e.png">

**Comment by SiAdcock** [comment]
This is interesting, I will return to using `display:flex`, thanks @liywjl 

Can I get a quick confirmation: is the screenshot here from a real use case? In [the Radio docs we recommend](https://www.theguardian.design/2a1e5182b/p/2891dd-radio-button/b/46940d/t/376e27) using horizontal radio buttons if there are only 2 answers.

**Comment by liywjl** [comment]
Thank you for mentioning that, I made a fix on DCR to conditionally determine the orientation https://github.com/guardian/dotcom-rendering/pull/2034
