### ISSUE TITLE
Animation overlay span in Checkbox intercepts Selenium click events aimed at the underlying input

### ISSUE THREAD

**Issue by i-hardy** [guardian/source#663]
**Describe the bug**
When running our Selenium tests against the Subscriptions checkouts, the tests are failing on Source checkboxes due to the span that provides the tick animation intercepting the click event. An example of a failed test run is here: https://travis-ci.org/github/guardian/support-frontend/builds/750209284

The same behavior appears whether using `clickOn` or the `checkbox(selector).select()` methods from ScalaTest. However the problem is fixed if the offending span has `pointer-events: none` applied, which does not seem to otherwise effect the component in any way.

**To Reproduce**
Clone [support-frontend](https://github.com/guardian/support-frontend/) and rewind to commit 187be8a, then run the Selenium tests with `sbt selenium:test`. The tests will fail when attempting to check out using direct debit, as the checkbox to confirm that a user is the account holder cannot be clicked.

**Expected behavior**
The checkbox should be clickable using Selenium in order to verify the expected behaviour of the checkout as a whole.

The fix for this is really tiny- it's just applying `pointer-events: none` to that span in the Checkbox component- so I'm happy to raise a PR to fix this myself if you'd like!

**Comment by SiAdcock** [comment]
Thanks @i-hardy ! I’m on holiday for Christmas, but happy to accept a PR if you have time 🙂 I wonder if the same issue affects radio buttons too?

**Comment by i-hardy** [comment]
The tests interact with the radio buttons too and don't seem to have the same issue, although it might be worth applying the same fix there too just in case if there's no visual regressions. I'll get a PR in 🙂
