### ISSUE TITLE
Inclusion of new gift icon

### ISSUE THREAD

**Issue by GHaberis** [guardian/source#665]
We've had to introduce a new svg gift box icon into the main navigation for "gifting" on `frontend` and `dotcom-rendering`, it'd be good to get this in source. Can I just raise a PR to include it?

<img width="124" alt="Screenshot 2020-12-21 at 11 51 02" src="https://user-images.githubusercontent.com/1590704/102774401-d1d2e180-4382-11eb-8d5e-1149f96a69a8.png">

**Comment by SiAdcock** [comment]
Thanks for raising this @GHaberis. I'll discuss this with @akemitakagi when she's back in the office. The icon is not currently in our Figma library, so we'll need to add it or consider alternatives. When we have an icon in Figma, we can add it to the codebase – your help in doing this will be greatly appreciated 😍 

I'll get back to you tomorrow.

**Comment by SiAdcock** [comment]
@akemitakagi will work with designers to ensure this gets added to Figma.

@GHaberis would you be able to raise a PR adding it to the [icons](https://github.com/guardian/source/tree/main/src/core/icons) package? 🙏

**Comment by SiAdcock** [comment]
The Gift Icon is now available in Figma:

https://www.figma.com/file/Ai7AELHC6KCz38qKZkvuHo/Icons?node-id=355%3A0
